spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
