spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
